### ISSUE TITLE
Definer og implementer eksempel for front-end ekvivalent av contract-tests

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/a-front-end-service#6]
- [x]  definere kontrakt test
- [x] implementere eksempel
- [ ] Typescript (?)

**Comment by rannveigskjerve** [comment]
Typescriptfiler kjører via codeceptjs, men tsc plukker ikke opp typene fra node modulen (fører til feil og manglende autocomplete i VisualStudio)
